feat: add zellij config

diff --git a/etc/zshrc b/etc/zshrc
--- a/etc/zshrc
+++ b/etc/zshrc
@@ -124,25 +124,19 @@ fi
 declare -A ZINIT
 ZINIT[NO_ALIASES]=1
 source "${ZINIT_HOME}/bin/zinit.zsh"
-# autoload -Uz _zinit
-# (( ${+_comps} )) && _comps[zinit]=_zinit
 
 #zinit light Aloxaf/fzf-tab
-
-zinit ice wait'0' lucid; zinit light changyuheng/fz
-FZ_HISTORY_CD_CMD=_zlua
-
-zinit ice wait'0' lucid; zinit light zsh-users/zsh-history-substring-search
-bindkey -M emacs '^p' history-substring-search-up
-bindkey -M emacs '^n' history-substring-search-down
-
 zinit light zsh-users/zsh-autosuggestions
 bindkey '^f' autosuggest-accept
 
+zinit ice wait'0' lucid; zinit light changyuheng/fz
+FZ_HISTORY_CD_CMD=_zlua
+zinit ice wait'0' lucid; zinit light zsh-users/zsh-history-substring-search
+bindkey -M emacs '^p' history-substring-search-up
+bindkey -M emacs '^n' history-substring-search-down
 zinit ice wait'0' lucid atinit'zpcompinit; zpcdreplay'
 zinit light zsh-users/zsh-syntax-highlighting
-
-zinit ice wait'0' blockf lucid atload'zsh_after_init'
+zinit ice wait'1' blockf lucid atload'zsh_after_init'
 zinit light zsh-users/zsh-completions
 
 function zsh_after_init() {
@@ -228,12 +222,37 @@ function zlua_install() {
 }
 
 # tmux {{{
-if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
-    mkdir -p "$HOME/.tmux/plugins" && pushd "$_"
-    git clone https://github.com/tmux-plugins/tpm --depth 1
-    popd
-    ~/.tmux/plugins/tpm/bin/install_plugins
+if [ -f "$HOME/.tmux.conf" ]; then
+    if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
+        mkdir -p "$HOME/.tmux/plugins" && pushd "$_"
+        git clone https://github.com/tmux-plugins/tpm --depth 1
+        popd
+        ~/.tmux/plugins/tpm/bin/install_plugins
+    fi
 fi
+function tmux_attach {
+    if [ -n "$TMUX" ]; then
+        echo "Error: You are already inside a tmux session."
+        return 1
+    fi
+    local session_name="${1:-dev}"
+    if [ -z "$session_name" ]; then
+        # try connect last session
+        tmux attach-session 2>/dev/null
+    else
+        tmux attach-session -t "$session_name" 2>/dev/null
+    fi
+    if [ $? -ne 0 ]; then
+        # add sleep fix "server exited unexpectedly" in some platform
+        sleep 0.00001
+        tmux new-session -s "$session_name"
+    fi
+}
+alias ta='tmux_attach'
+alias tl=' tmux ls'
+alias tk=' tmux kill-session'
+alias tka=' tmux kill-server'
+
 
 # nix {{{
 NIX_MIRROR=${NIX_MIRROR:-"cn"}
@@ -531,19 +550,14 @@ alias ll='ls -alh --time-style=long-iso'
 alias docker_autoremove='docker rmi $(docker images -f "dangling=true" -q)'
 alias lg='lazygit'
 
-# tmux {{{
-function tmux_attach {
-    local attach=""
-    local new=""
-    [ -n "$TMUX" ] && echo "not run tmux inside tmux" && return
-    [ -n "$1" ] && attach="-t$1" && new="-s$1"
-    tmux a $attach 2>/dev/null
-    # add sleep fix "server exited unexpectedly" in some platform
-    [ "$?" -ne 0 ] && sleep 0.0001 && tmux new $new
+function zellij_attach {
+    [ -n "$ZELLIJ" ] && echo "Error: Zellij is already running inside Zellij." && return
+    local session_name="${1:-dev}"
+    zellij a -c $session_name 2>/dev/null
 }
-alias ta='tmux_attach'
-alias tl=' tmux ls'
-alias tk=' tmux kill-server'
+alias zj='zellij'
+alias za='zellij_attach'
+alias zl=' zellij ls'
 
 alias rs='rsync -rval --partial --delete --progress '
 alias cpa='cp -rfavx '
